# Generated by Django 4.2.7 on 2024-11-26 12:33

import campaigns.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(10.0)])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(choices=[('Medical', 'Medical'), ('Education', 'Education'), ('Disaster Relief', 'Disaster Relief'), ('Environmental Conservation', 'Environmental Conservation'), ('Social Justice', 'Social Justice'), ('Animal Welfare', 'Animal Welfare'), ('Community Development', 'Community Development'), ('Non-profit Support', 'Non-profit Support'), ('Arts and Culture', 'Arts and Culture'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('banner_image', models.ImageField(upload_to='campaign_banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), campaigns.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('contact_info', models.EmailField(max_length=254)),
                ('story', models.TextField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('total_donors', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
