# Generated by Django 5.1.3 on 2024-12-08 17:39

import campaigns.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='banner_image',
            field=models.ImageField(help_text='Upload a banner image for the campaign (max 10MB).', upload_to='campaign_banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), campaigns.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Education', 'Education'), ('Disaster Relief', 'Disaster Relief'), ('Environmental Conservation', 'Environmental Conservation'), ('Social Justice', 'Social Justice'), ('Animal Welfare', 'Animal Welfare'), ('Community Development', 'Community Development'), ('Non-profit Support', 'Non-profit Support'), ('Arts and Culture', 'Arts and Culture'), ('Other', 'Other')], help_text='Category of the campaign.', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='contact_info',
            field=models.EmailField(help_text='Provide contact information for inquiries.', max_length=254),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the campaign was created.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(help_text='User who created the campaign.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current amount raised for this campaign.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(help_text='Provide details about the campaign.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(help_text='Enter the campaign end date.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, help_text='Set a goal amount for the campaign.', max_digits=10, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.CharField(help_text='Location of the campaign.', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', help_text='Current status of the campaign.', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='story',
            field=models.TextField(blank=True, help_text='Share the story behind the campaign.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(help_text='Enter a campaign title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_donors',
            field=models.PositiveIntegerField(default=0, help_text='Total number of donors contributed to this campaign.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of views on the campaign.'),
        ),
        migrations.AlterField(
            model_name='campaignrequest',
            name='category',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Education', 'Education'), ('Disaster Relief', 'Disaster Relief'), ('Environmental Conservation', 'Environmental Conservation'), ('Social Justice', 'Social Justice'), ('Animal Welfare', 'Animal Welfare'), ('Community Development', 'Community Development'), ('Non-profit Support', 'Non-profit Support'), ('Arts and Culture', 'Arts and Culture'), ('Other', 'Other')], help_text='Category of the requested campaign.', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaignrequest',
            name='description',
            field=models.TextField(help_text='Description of the campaign request.'),
        ),
        migrations.AlterField(
            model_name='campaignrequest',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, help_text='Goal amount for the campaign request.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaignrequest',
            name='location',
            field=models.CharField(help_text='Proposed location of the campaign.', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaignrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request was created.'),
        ),
        migrations.AlterField(
            model_name='campaignrequest',
            name='requester',
            field=models.ForeignKey(help_text='User who submitted the request.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaignrequest',
            name='title',
            field=models.CharField(help_text='Title of the campaign request.', max_length=200),
        ),
    ]
